Style/ClassAndModuleChildren:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/MethodName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
